- name: Add icmp rule to security group
  os_security_group_rule:
    security_group: "{{ _security_group }}"
    protocol: icmp
    port_range_min: -1
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0
  register: results

- name: Add icmp rule to security group - results
  debug: var=results

- name: Add tcp rule to security group port 22
  os_security_group_rule:
    security_group: "{{ _security_group }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  register: results

- name: Add tcp rule to security group port 22 - results
  debug: var=results

- name: Add tcp rule to security group port 3389 - results
  os_security_group_rule:
    security_group: "{{ _security_group }}"
    protocol: tcp
    port_range_min: 3389
    port_range_max: 3389
    remote_ip_prefix: 0.0.0.0/0
  register: results

- name: Add tcp rule to security group port 3389 - results
  debug: var=results
