- name: Check if SSH key exists
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ _key_abspath }}"
    - "{{ _key_abspath }}.pub"
  register: results

- name: Check if SSH key exists - results
  debug: var=results

- name: Create SSH key
  shell: "ssh-keygen -b 2048 -t rsa -f {{ _key_abspath }} -q -N ''"
  register: results

- name: Create SSH key - results
  debug: var=results

- name: Check to make sure SSH key was created
  stat:
    path: "{{ _key_abspath }}"
  register: results

- name: Fail if SSH key not found
  fail:
    msg: "Unable to find SSH keys, maybe generation was not successful?"
  when: results.stat.exists == false
