# Playbook adds rules for (icmp, tcp - ssh/rdp) to a security group

- name: Add rules to a security group
  hosts: "{{ hosts | default('localhost') }}"

  vars:
    _security_group: "{{ security_group | default('default') }}"

  tasks:
    - os_security_group_rule:
        security_group: "{{ _security_group }}"
        protocol: icmp
        port_range_min: -1
        port_range_max: -1
        remote_ip_prefix: 0.0.0.0/0
      register: result

    - debug: var=result

    - os_security_group_rule:
        security_group: "{{ _security_group }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
      register: result

    - debug: var=result

    - os_security_group_rule:
        security_group: "{{ _security_group }}"
        protocol: tcp
        port_range_min: 3389
        port_range_max: 3389
        remote_ip_prefix: 0.0.0.0/0
      register: result

    - debug: var=result
