# Playbook adds a key pair to tenant to be used with instances creation.
# It assumes the SSH public key was already generated.

- name: Add key pair to tenant
  hosts: "{{ hosts | default('localhost') }}"

  vars:
    _public_key: "{{ public_key | default('cloud_rsa.pub') }}"
    _public_keyname: "{{ public_keyname | default('cloud') }}"

  tasks:
    - stat:
        path: "{{ _public_key }}"
      register: result

    - fail:
        msg: "SSH public key: {{ _public_key }} does not exist!"
      when: result.stat.exists == false

    - os_keypair:
        state: present
        name: "{{ _public_keyname }}"
        public_key_file: "{{ _public_key }}"
      register: result

    - debug: var=result
