# Playbook creates keys to be used by SSH protocol via ssh-keygen.
# This does not prompt for passphrase, good for test automation.

- name: Create keys for SSH protocol
  hosts: "{{ hosts | default('localhost') }}"

  vars:
    _keyname: "{{ keyname | default('cloud_rsa') }}"

  tasks:
    - name: ssh-keygen
      shell: "ssh-keygen -b 2048 -t rsa -f {{ _keyname }} -q -N ''"

    - stat:
        path: ./{{ _keyname }}
      register: result

    - fail:
        msg: "Unable to find SSH keys, maybe generation was not successful?"
      when: result.stat.exists == false
