# Playbook configures trystack networks. Creates internal network, connected
# to a external network by a router created.

- name: Configure trystack OpenStack network
  hosts: "{{ hosts | default('localhost') }}"

  vars:
    _in_network: "{{ in_network | default('internal') }}"
    _out_network: "{{ out_network | default('public') }}"
    _subnet: "{{ subnet | default('192.168.52.0/24') }}"
    _router: "{{ router | default('router') }}"

  tasks:
    - os_network:
        name: "{{ _in_network }}"
        external: no
      register: result

    - debug: var=result

    - os_subnet:
        state: present
        name: "{{ _in_network }}"
        network_name: "{{ _in_network }}"
        cidr: "{{ _subnet }}"
      register: result

    - debug: var=result

    - os_router:
        state: present
        name: "{{ _router }}"
        network: "{{ _out_network }}"
        interfaces: "{{ _in_network }}"
      register: result

    - debug: var=result
